[package]
name = "smsc9512"
version = "0.1.0"
authors = ["Li Zhuohua <lizhuohua1994@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
linux-kernel-module = { path = ".." }
rlibc = "1.0.0"

[profile.release]
panic = "abort"
lto = true

[profile.dev]
panic = "abort"
